//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using LOGI.Framework.Toolkit.Core.SendMessage.Model;

namespace LOGI.Framework.Toolkit.Core.SendMessage.Email.Provider.Database
{
    public partial class LOGIToolkitMessageQueueEntities : ObjectContext
    {
        public const string ConnectionString = "name=LOGIToolkitMessageQueueEntities";
        public const string ContainerName = "LOGIToolkitSendMessageModel";
    
        #region Constructors
    
        public LOGIToolkitMessageQueueEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public LOGIToolkitMessageQueueEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public LOGIToolkitMessageQueueEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<EmailQueue> EmailQueue
        {
            get { return _emailQueue  ?? (_emailQueue = CreateObjectSet<EmailQueue>("EmailQueue")); }
        }
        private ObjectSet<EmailQueue> _emailQueue;

        #endregion

    }
}
