//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using LOGI.Framework.Toolkit.Foundation.Repository;

namespace LOGI.Framework.Toolkit.Core.SendMessage.Model
{
    public partial class EmailQueue:EntityBase
    {
        public EmailQueue()
        {
            this.QueueDate = DateTime.Now;
        }
        #region Primitive Properties
    
        public virtual int EmailID
        {
            get;
            private set;
        }
    
        public virtual System.DateTime QueueDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> SendDate
        {
            get;
            private set;
        }
    
        public virtual string EmailTo
        {
            get;
            set;
        }
    
        public virtual string EmailFrom
        {
            get;
            set;
        }
    
        public virtual string EmailSubject
        {
            get;
            set;
        }
    
        public virtual string EmailBody
        {
            get;
            set;
        }
    
        public virtual string EmailCC
        {
            get;
            set;
        }
    
        public virtual string EmailBCC
        {
            get;
            set;
        }
    
        public virtual int EmailPriority
        {
            get;
            set;
        }


        public virtual int EmailStatus
        {
            get;
            set;
        }

        #endregion
    }
}
