//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using LOGI.Framework.Toolkit.Core.SendMessage.Model;

namespace LOGI.Framework.Toolkit.Core.SendMessage.Sms.Provider.Database
{
    public partial class YKMToolkitSMSQueueEntities : ObjectContext
    {
        public const string ConnectionString = "name=YKMToolkitSMSQueue";
        public const string ContainerName = "YKMToolkitSMSQueue";
    
        #region Constructors
    
        public YKMToolkitSMSQueueEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public YKMToolkitSMSQueueEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }

        public YKMToolkitSMSQueueEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<SMSQueue> SMSQueue
        {
            get { return _sMSQueue  ?? (_sMSQueue = CreateObjectSet<SMSQueue>("SMSQueue")); }
        }
        private ObjectSet<SMSQueue> _sMSQueue;

        #endregion

    }
}
